CREATE TABLE `TeamCareerBatting` (
	`yearID` SMALLINT(6) NULL DEFAULT NULL,
	`teamID` VARCHAR(3) NULL DEFAULT NULL,
	`lgID` VARCHAR(2) NULL DEFAULT NULL,
	`AB` INT(6) UNSIGNED NOT NULL DEFAULT '0',
	`R` INT(6) UNSIGNED NOT NULL DEFAULT '0',
	`H` INT(6) UNSIGNED NOT NULL DEFAULT '0',
	`2B` INT(6) UNSIGNED NOT NULL DEFAULT '0',
	`3B` INT(6) UNSIGNED NOT NULL DEFAULT '0',
	`HR` INT(6) UNSIGNED NOT NULL DEFAULT '0',
	`RBI` INT(6) UNSIGNED NOT NULL DEFAULT '0',
	`SB` INT(6) UNSIGNED NOT NULL DEFAULT '0',
	`CS` INT(6) UNSIGNED NOT NULL DEFAULT '0',
	`BB` INT(6) UNSIGNED NOT NULL DEFAULT '0',
	`SO` INT(6) UNSIGNED NOT NULL DEFAULT '0',
	`IBB` INT(6) UNSIGNED NOT NULL DEFAULT '0',
	`HBP` INT(6) UNSIGNED NOT NULL DEFAULT '0',
	`SH` INT(6) UNSIGNED NOT NULL DEFAULT '0',
	`SF` INT(6) UNSIGNED NOT NULL DEFAULT '0',
	`GIDP` INT(6) UNSIGNED NOT NULL DEFAULT '0',
	`BattingAvg` DECIMAL(5,4) UNSIGNED NOT NULL DEFAULT '0.0000',
	`OnBaseAvg` DECIMAL(5,4) UNSIGNED NOT NULL DEFAULT '0.0000',
	`SluggingAvg` DECIMAL(5,4) UNSIGNED NOT NULL DEFAULT '0.0000',
	UNIQUE INDEX `yearID_teamID` (`yearID`, `teamID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

